name: CD Pipeline

on:
  workflow_run:
    workflows: [ "CI Pipeline" ]
    types:
      - completed

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: pull docker image
        run:  docker pull adarsh6672/unleash-userservice
      - name: delete old docker image
        run:  docker rm -f user-service || true
      - name: run docker container
        run:  docker run -d -p 8081:8081 --name user-service --network compose_app-network adarsh6672/unleash-userservice

